### ISSUE TITLE
Unable to preview and submit issue

### ISSUE THREAD

**Issue by cyberxnomad** [element-plus/element-plus-issue-helper#1]
When clicking the preview button, the following error message appears in the console:  
```
ReferenceError: resolveReproductionLink is not defined
    at hx (index.47e8119d.js:95:47)
    at jl.fn (index.47e8119d.js:138:275)
    at jl.run (index.47e8119d.js:1:5948)
    at Zh.get value [as value] (index.47e8119d.js:1:14031)
    at jl.fn (index.47e8119d.js:138:347)
    at jl.run (index.47e8119d.js:1:5948)
    at Zh.get value [as value] (index.47e8119d.js:1:14031)
    at index.47e8119d.js:140:521
    at r (index.47e8119d.js:4:3612)
    at Ee (index.47e8119d.js:4:12640)
```

**Comment by arnauddoub** [comment]
Same error

**Comment by JackieCheung** [comment]
+1

**Comment by mxp131011** [comment]
+1

**Comment by mghcool** [comment]
+1

**Comment by jw-foss** [comment]
Hey guys, I have already found the root cause, and I will fix it ASAP. Sorry for keeping you waiting.
